[package]
name = "rustreexo"
version = "0.1.0"
authors = ["Calvin Kim <calvin@kcalvinalvin.info>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
bitcoin_hashes = "0.12.0"
lazy_static = "1.4.0"

[dev-dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.81"

[workspace]
members = [".", "c-rustreexo"]