[package]
name = "rustreexo"
version = "0.1.0"
authors = ["Calvin Kim <calvin@kcalvinalvin.info>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
bitcoin_hashes = "^0.11.0"
sha2 = "0.10.2"

[dev-dependencies]
serde_json="1.0.81"
