[package]
name = "nodejs-wasm"
version = "0.1.0"
edition = "2021"

[lib]
name = "rustreexo"
crate-type = ["cdylib", "staticlib", "rlib"]

[dependencies]
rustreexo = { path = "../" }
bitcoin_hashes = "0.11"
wasm-bindgen = "0.2.87"
js-sys = "0.3.64"
